# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'ReddiTech' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'OAuthSwift', '~> 2.2.0'

  # Pods for ReddiTech

  target 'ReddiTechTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ReddiTechUITests' do
    # Pods for testing
  end

end
